# Generated by Django 4.0.6 on 2022-07-28 18:58

from django.db import migrations


def populate_status(apps, schemaeditro):
    statuses = {
        "published": "Content that is displayed on the site",
        "pending_review": "Content that has not yet been validated by an editor",
        "revison_requested": "Content that requires modifications based on an editorial review",
        "denied": "Content that will not be displaed on the site",
        "draft": "A work in progress"
    }
    Status = apps.get_model("articles", "Status")
    for name, desc in statuses.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_status_article_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        
    ]
